add(new Array('0'), 'Click');
add(new Array('1'), 'Creacion');
add(new Array('0', '3'), 'Crear');
add(new Array('0', '1', '3'), 'FACILWEB');
add(new Array('2'), 'Inicio');
add(new Array('0'), 'Youtube');
add(new Array('0', '1', '3'), 'aqui');
add(new Array('1', '3'), 'click');
add(new Array('3'), 'copias');
add(new Array('0', '1'), 'creacion');
add(new Array('0', '1', '3'), 'enlace');
add(new Array('0', '1', '3'), 'este');
add(new Array('3'), 'manejo');
add(new Array('0'), 'producto');
add(new Array('0', '1'), 'productos');
add(new Array('0', '1', '3'), 'puedes');
add(new Array('1'), 'rapida');
add(new Array('3'), 'respectiva');
add(new Array('3'), 'restauracion');
add(new Array('3'), 'restaurar');
add(new Array('3'), 'seguridad');
add(new Array('0', '1', '3'), 'video');
add(new Array('2'), 'ÂFacilWeb');