<?php

return [
    'app' => [
        'name' => 'Biblia para todos',
        'env' => getenv('APP_ENV') ?: 'local',
        'base_path' => dirname(__DIR__),
        'base_url' => getenv('APP_URL') ?: '/',
        'public_url' => getenv('APP_PUBLIC_URL') ?: '',
        'timezone' => getenv('APP_TZ') ?: 'America/Bogota',
    ],
    'paths' => [
        'bible' => dirname(__DIR__) . DIRECTORY_SEPARATOR . (getenv('BIBLE_DB') ?: '01RVR1960x.bbli'),
        'bible_plain' => dirname(__DIR__) . DIRECTORY_SEPARATOR . (getenv('BIBLE_PLAIN_DB') ?: '01RVR1960.bbli'),
        'bible_compare' => dirname(__DIR__) . DIRECTORY_SEPARATOR . (getenv('BIBLE_COMPARE_DB') ?: (getenv('BIBLE_PLAIN_DB') ?: '01RVR1960.bbli')),
        'bible_strong' => dirname(__DIR__) . DIRECTORY_SEPARATOR . (getenv('BIBLE_STRONG_DB') ?: 'es_rv1909.bbli'),
        'commentary' => dirname(__DIR__) . DIRECTORY_SEPARATOR . (getenv('COMMENTARY_DB') ?: '01RVR1960x.cmti'),
        'lexicon' => dirname(__DIR__) . DIRECTORY_SEPARATOR . (getenv('LEXICON_DB') ?: 'strong.lexx'),
        'devotional' => dirname(__DIR__) . DIRECTORY_SEPARATOR . (getenv('DEVOTIONAL_DB') ?: 'spurgeon.devx'),
        'app_db' => dirname(__DIR__) . DIRECTORY_SEPARATOR . 'storage' . DIRECTORY_SEPARATOR . 'app.sqlite',
    ],
    'versions' => [
        'primary_label' => getenv('BIBLE_PRIMARY_LABEL') ?: 'RVR60',
        'compare_label' => getenv('BIBLE_COMPARE_LABEL') ?: 'Versión 2',
    ],
    'ai' => [
        'provider' => 'openai',
        'enabled' => getenv('AI_ENABLED') === '1',
        'model' => getenv('OPENAI_MODEL') ?: 'gpt-4.1-mini',
        'api_key' => getenv('OPENAI_API_KEY') ?: '',
    ],
    'mail' => [
        'enabled' => getenv('MAIL_ENABLED') === '1',
        'host' => getenv('MAIL_HOST') ?: '',
        'port' => (int) (getenv('MAIL_PORT') ?: 587),
        'encryption' => getenv('MAIL_ENCRYPTION') ?: 'tls',
        'timeout' => (int) (getenv('MAIL_TIMEOUT') ?: 20),
        'ehlo_name' => getenv('MAIL_EHLO_NAME') ?: 'bibliasoft.local',
        'allow_self_signed' => getenv('MAIL_ALLOW_SELF_SIGNED') === '1',
        'from_email' => getenv('MAIL_FROM_EMAIL') ?: '',
        'from_name' => getenv('MAIL_FROM_NAME') ?: 'Biblia para todos',
        'username' => getenv('MAIL_USERNAME') ?: '',
        'password' => getenv('MAIL_PASSWORD') ?: '',
    ],
    'admin' => [
        'route' => getenv('SUPERADMIN_ROUTE') ?: 'superadmin',
        'user_id' => (int) (getenv('SUPERADMIN_USER_ID') ?: 1),
        'email' => getenv('SUPERADMIN_EMAIL') ?: '',
    ],
    'recaptcha' => [
        'enabled' => getenv('RECAPTCHA_ENABLED') === '1',
        'provider' => getenv('RECAPTCHA_PROVIDER') ?: 'legacy',
        'mode' => getenv('RECAPTCHA_MODE') ?: 'checkbox',
        'site_key' => getenv('RECAPTCHA_SITE_KEY') ?: '',
        'secret_key' => getenv('RECAPTCHA_SECRET_KEY') ?: '',
        'project_id' => getenv('RECAPTCHA_PROJECT_ID') ?: '',
        'api_key' => getenv('RECAPTCHA_API_KEY') ?: '',
        'expected_action' => getenv('RECAPTCHA_EXPECTED_ACTION') ?: 'register',
        'min_score' => (float) (getenv('RECAPTCHA_MIN_SCORE') ?: 0.5),
        'verify_hostname' => getenv('RECAPTCHA_VERIFY_HOSTNAME') !== '0',
        'timeout' => (int) (getenv('RECAPTCHA_TIMEOUT') ?: 10),
    ],
    'security' => [
        'login_window_seconds' => 900,
        'login_max_attempts' => 10,
        'register_window_seconds' => 3600,
        'register_max_attempts' => 8,
    ],
    'search' => [
        'default_limit' => 60,
        'use_fts_preferred' => true,
    ],
];
